name: Alya
favicon: null
layout_spectrum: 0.23429
typography_spectrum: 0.50674
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3b5860'
    - '#c69960'
    - '#ebdc7d'
    - '#75766e'
    - '#f9f9d3'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
