name: Alya
favicon: null
layout_spectrum: 0.64085318823345
typography_spectrum: 0.457348495721817
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9520659651607275
  lightness: 0.7114476158749312
  saturation: 0.5438731897156686
  rhythmicContrast: 0.15413106582127512
purpose: []
